version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - zip function.zip lambda_function.py

artifacts:
  files:
    - function.zip
  name: BuildArtifact
